select * from SUICIDE_USER.suicide_statistics;

--Basic Statistics
SELECT 
    MIN(TOTAL) AS MIN_SUICIDES,
    MAX(TOTAL) AS MAX_SUICIDES,
    AVG(TOTAL) AS AVG_SUICIDES,
    MEDIAN(TOTAL) AS MEDIAN_SUICIDES,
    STDDEV(TOTAL) AS STDDEV_SUICIDES
FROM SUICIDE_STATISTICS;


-- Total Suicides by Year
SELECT YEAR, SUM(TOTAL) AS TOTAL_SUICIDES 
FROM SUICIDE_STATISTICS 
GROUP BY YEAR 
ORDER BY YEAR;

--Top 5 States with Highest Suicides
SELECT STATE, SUM(TOTAL) AS TOTAL_SUICIDES 
FROM SUICIDE_STATISTICS 
GROUP BY STATE 
ORDER BY TOTAL_SUICIDES DESC 
FETCH FIRST 5 ROWS ONLY;

-- Suicide Trends by Gender
SELECT GENDER, SUM(TOTAL) AS TOTAL_SUICIDES 
FROM SUICIDE_STATISTICS 
GROUP BY GENDER;

--Most Affected Age Group
SELECT AGE_GROUP, SUM(TOTAL) AS TOTAL_SUICIDES 
FROM SUICIDE_STATISTICS 
GROUP BY AGE_GROUP 
ORDER BY TOTAL_SUICIDES DESC;

--Year-over-Year Growth in Suicides
SELECT YEAR, 
       SUM(TOTAL) AS TOTAL_SUICIDES, 
       LAG(SUM(TOTAL)) OVER (ORDER BY YEAR) AS PREV_YEAR_SUICIDES,
       ROUND(((SUM(TOTAL) - LAG(SUM(TOTAL)) OVER (ORDER BY YEAR)) / 
               LAG(SUM(TOTAL)) OVER (ORDER BY YEAR)) * 100, 2) AS YOY_GROWTH
FROM SUICIDE_STATISTICS
GROUP BY YEAR
ORDER BY YEAR;

--Ranking States by Suicide Rate
SELECT STATE, SUM(TOTAL) AS TOTAL_SUICIDES,
       RANK() OVER (ORDER BY SUM(TOTAL) DESC) AS RANKING
FROM SUICIDE_STATISTICS
GROUP BY STATE
order by RANKING DESC;

--The Most Common Suicide Causes
SELECT TYPE, SUM(TOTAL) AS TOTAL_SUICIDES
FROM SUICIDE_STATISTICS
GROUP BY TYPE
ORDER BY TOTAL_SUICIDES DESC
FETCH FIRST 5 ROWS ONLY;


select distinct state from suicide_statistics;