LOAD DATA
INFILE 'suicide_data.csv'
BADFILE 'suicide_data.bad'
DISCARDFILE 'suicide_data.dis'
APPEND
INTO TABLE SUICIDE_STATISTICS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' 
TRAILING NULLCOLS
(
  STATE        CHAR(100),
  YEAR         INTEGER EXTERNAL,
  TYPE_CODE    CHAR(100),
  TYPE         CHAR(255),
  GENDER       CHAR(10),
  AGE_GROUP    CHAR(50),
  TOTAL        INTEGER EXTERNAL "CASE WHEN :TOTAL IS NULL OR :TOTAL = '' THEN 0 ELSE TO_NUMBER(:TOTAL) END"
)
