--Check null values 
SELECT * FROM SUICIDE_STATISTICS
WHERE STATE IS NULL OR YEAR IS NULL OR TOTAL IS NULL;

--Remove Duplicates
DELETE FROM SUICIDE_STATISTICS
WHERE ROWID NOT IN (
    SELECT MIN(ROWID) 
    FROM SUICIDE_STATISTICS 
    GROUP BY STATE, YEAR, TYPE_CODE, TYPE, GENDER, AGE_GROUP
);

--Standardizing Gender Values
UPDATE SUICIDE_STATISTICS 
SET GENDER = UPPER(TRIM(GENDER))
WHERE GENDER NOT IN ('MALE', 'FEMALE');


-- Fixing Age Group Formatting
UPDATE SUICIDE_STATISTICS
SET AGE_GROUP = TRIM(AGE_GROUP); 